# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr: none

trigger: none

pool: sonicbld


variables:
  IMAGE_DISTRO: bullseye

- stage: Test
  jobs:
  - job: test
    container:
      image: sonicdev-microsoft.azurecr.io:443/sonic-slave-$(bullseye):latest
    steps:
    - script:
        echo test
      continueOnError: True
      displayName: 'Run a one-line script'
