# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr: none

trigger: none

pool: sonicbld


variables:
  IMAGE_DISTRO: bullseye
  IMAGE: sonicdev-microsoft.azurecr.io:443/sonic-slave-bullseye:latest

stages:
- stage: Build
  jobs:
  - job: build
    steps:
    - script:
        IMAGE_DISTRO=buster
        SLAVE_DOCKER_IMAGE="sonicdev-microsoft.azurecr.io:443/sonic-slave-$IMAGE_DISTRO:latest"
        echo SLAVE_DOCKER_IMAGE=$SLAVE_DOCKER_IMAGE
        echo "##vso[task.setvariable variable=SLAVE_DOCKER_IMAGE;isOutput=true]$SLAVE_DOCKER_IMAGE"
      name: SetVar
      displayName: "Check if vstest is needed."
- stage: Test
  dependsOn: Build
  jobs:
  - job: test
    pool: sonictest
    variables:
      SLAVE_DOCKER_IMAGE: $[ stageDependencies.Build.outputs['build.SetVar.SLAVE_DOCKER_IMAGE'] ]
    container:
      image: sonicdev-microsoft.azurecr.io:443/sonic-slave-bullseye:latest
      options: --privileged -v /lib/modules:/lib/modules 
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y kmod
        sudo modprobe ib_core
        sudo modprobe team
        echo test
      continueOnError: True
      displayName: 'Run a one-line script'
