# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool: sonic-image-builder-1ES

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo triggerDefinitionName=$(Build.TriggeredBy.DefinitionName)
    echo runId=$(resources.pipeline.test-workflow.runID)
    echo triggerSourceBranch=$(resources.pipeline.test-workflow.sourceBranch)
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    for i in $(seq 1 1000)
    do
      wget https://packages.trafficmanager.net/public/packages/hiredis_0.14.0.orig.tar.gz-6d565680a4af0d2e261abbc3e3431b2b -O hiredis_0.14.0.orig.tar.gz
    done
  displayName: 'Run a multi-line script'
