# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - 202012
    - 202???
    - 201[9]11
    exclude:
    - 202006

resources:
 pipelines:
   - pipeline: test-workflow
     source: xumia.test-workflow
     trigger:
      enabled: true
      branches:
       include:
         - '*'

parameters:
  - name: Test
    type: number
    default: 141

variables:
- name: BUILD_BRANCH
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    value: $(System.PullRequest.TargetBranch)
  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    value: $(Build.SourceBranch)

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo BUILD_BRANCH=$(BUILD_BRANCH)
    echo triggerDefinitionName=$(Build.TriggeredBy.DefinitionName)
    echo runId=$(resources.pipeline.test-workflow.runID)
    echo triggerSourceBranch=$(resources.pipeline.test-workflow.sourceBranch)
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
